// AI Arena — Tool Database (Jan 2026, sourced from a16z Top 100 Gen AI + current data)

const TOOL_CATEGORIES = {
  assistant: { name: 'AI Assistants', icon: '💬', desc: 'General-purpose AI chatbots and assistants' },
  coding: { name: 'Coding & App Building', icon: '💻', desc: 'AI tools for writing code and building apps' },
  image: { name: 'Image Generation', icon: '🎨', desc: 'AI tools for creating and editing images' },
  video: { name: 'Video Generation', icon: '🎬', desc: 'AI tools for creating and editing video' },
  audio: { name: 'Audio & Music', icon: '🎵', desc: 'AI tools for voice, music, and audio' },
  research: { name: 'Research & Productivity', icon: '📚', desc: 'AI tools for research, writing, and getting work done' },
};

const TOOLS = [
  // === AI ASSISTANTS ===
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    maker: 'OpenAI',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/openai/ffffff',
    color: '#10a37f',
    colorRgb: '16,163,127',
    tagline: 'The #1 AI assistant in the world',
    model: 'GPT-4o, o3, o1',
    launched: '2022',
    users: '300M+ weekly users',
    pricing: { free: 'Free (GPT-4o mini)', pro: '$20/mo (Plus)', top: '$200/mo (Pro)' },
    ratings: { coding: 8.5, writing: 8.0, reasoning: 9.0, speed: 8.5, vision: 8.5, creative: 8.0, value: 7.0 },
    ratingReasons: {
      coding: 'GPT-4o and o3 score top-tier on HumanEval and SWE-bench coding benchmarks',
      writing: 'Versatile writing across styles though occasionally verbose and hedgy',
      reasoning: 'o3 model achieves state-of-the-art on ARC-AGI and maths olympiad problems',
      speed: 'GPT-4o responds in under 2 seconds with streaming for most queries',
      vision: 'Strong image understanding plus DALL-E 3 image generation built in',
      creative: 'Good creative output with Custom GPTs and Canvas for collaborative work',
      value: 'Free tier is capable but Pro at $200/mo is steep for individual users'
    },
    topUseCases: ['Writing emails, essays, and professional documents', 'Generating and debugging code across any language', 'Creating images with DALL-E and analysing visual content'],
    pros: ['Most popular AI — huge ecosystem', 'GPT Store with custom GPTs', 'Voice & video mode', 'o3 for frontier reasoning', 'Canvas for collaborative editing'],
    cons: ['Pro tier expensive at $200/mo', 'Rate limits frustrate power users', 'Can be verbose and hedgy', 'Plugins ecosystem fragmented'],
    bestFor: 'The default AI for everything',
    simpleDesc: 'The world\'s most popular AI chatbot. Good at almost everything — writing, coding, maths, analysis, images. If you only try one AI tool, this is the one.',
    whoFor: 'Everyone — from students to professionals',
    url: 'https://chat.openai.com'
  },
  {
    id: 'claude',
    name: 'Claude',
    maker: 'Anthropic',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/anthropic/ffffff',
    color: '#d97757',
    colorRgb: '217,119,87',
    tagline: 'The thinking person\'s AI',
    model: 'Opus 4.5, Sonnet 4, Haiku 3.5',
    launched: '2023',
    users: 'Top 5 AI assistant globally',
    pricing: { free: 'Free (Sonnet)', pro: '$20/mo (Pro)', top: '$30/mo (Team)' },
    ratings: { coding: 9.5, writing: 9.5, reasoning: 9.5, speed: 7.5, vision: 8.0, creative: 9.0, value: 8.5 },
    ratingReasons: {
      coding: 'Opus 4.5 leads SWE-bench and real-world coding; Artifacts builds full apps inline',
      writing: 'Widely regarded as the best prose quality among all AI models',
      reasoning: 'Opus 4.5 excels at nuanced analysis with 200K context for deep reasoning',
      speed: 'Thorough but slower on complex tasks; Haiku offers fast lightweight responses',
      vision: 'Solid image understanding but cannot generate images natively',
      creative: 'Exceptional at creative writing, brainstorming, and nuanced artistic tasks',
      value: 'Pro at $20/mo with Opus 4.5 access is strong value for power users'
    },
    topUseCases: ['Writing long-form content, reports, and creative prose', 'Complex code generation and debugging with Artifacts', 'Analysing documents up to 200K tokens in length'],
    pros: ['Best writing quality of any AI', 'Opus 4.5 — frontier reasoning & code', '200K context window', 'Artifacts — builds apps inline', 'Honest about what it doesn\'t know'],
    cons: ['Smaller ecosystem than ChatGPT', 'Can be cautious on edgy topics', 'Slower on complex tasks', 'No image generation'],
    bestFor: 'Deep thinking, premium writing & code',
    simpleDesc: 'Known for exceptional writing and the deepest thinking. Opus 4.5 is considered one of the best AI models in the world for coding, analysis, and nuanced tasks.',
    whoFor: 'Writers, developers, analysts, and power users who value quality',
    url: 'https://claude.ai'
  },
  {
    id: 'gemini',
    name: 'Gemini',
    maker: 'Google',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/googlegemini/ffffff',
    color: '#4285f4',
    colorRgb: '66,133,244',
    tagline: 'Google\'s AI, everywhere',
    model: 'Gemini 2.5 Flash, 2.0 Pro',
    launched: '2023',
    users: '#2 AI assistant globally',
    pricing: { free: 'Free (very generous)', pro: '$20/mo (Advanced)', top: 'Vertex AI (enterprise)' },
    ratings: { coding: 8.0, writing: 7.5, reasoning: 8.5, speed: 9.0, vision: 9.0, creative: 8.5, value: 9.0 },
    ratingReasons: {
      coding: 'Competitive on benchmarks but slightly behind Claude and GPT-4o in practice',
      writing: 'Functional writing but lacks the polish and nuance of Claude or GPT-4o',
      reasoning: 'Gemini 2.0 Pro shows strong analytical ability with massive context window',
      speed: 'Flash model is one of the fastest available with excellent throughput',
      vision: 'Industry-leading multimodal — natively processes images, video, and audio',
      creative: 'Flash 2.5 native image generation went viral for quality; strong creative output',
      value: 'Best free tier in AI — Gemini 2.0 Flash is extremely capable at no cost'
    },
    topUseCases: ['Analysing images, PDFs, and videos with multimodal AI', 'Summarising and searching across Google Workspace', 'Processing extremely long documents with 1M+ token context'],
    pros: ['Deep Google Workspace integration', '1M+ token context — analyse huge docs', 'Excellent multimodal (images, video, audio)', 'Best free tier of any AI', 'Gemini Live for voice conversations', 'Flash 2.5 native image generation — went viral for quality'],
    cons: ['Quality can be inconsistent', 'Creative writing is weaker', 'Sometimes confidently wrong', 'Playing catch-up on coding'],
    bestFor: 'Google users & multimodal tasks',
    simpleDesc: 'Google\'s AI built into Gmail, Docs, Search, and Android. Flash 2.5\'s native image generation went viral for quality. Veo and Imagen accessible via Google AI Studio for power users. Best free tier available.',
    whoFor: 'Google Workspace users, researchers, anyone wanting a capable free AI',
    url: 'https://gemini.google.com'
  },
  {
    id: 'grok',
    name: 'Grok',
    maker: 'xAI',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/x/ffffff',
    color: '#1da1f2',
    colorRgb: '29,161,242',
    tagline: 'The unfiltered one',
    model: 'Grok 4',
    launched: '2023',
    users: '20M+ mobile users',
    pricing: { free: 'Limited via X', pro: '$8/mo (X Premium)', top: '$16/mo (Premium+)' },
    ratings: { coding: 8.0, writing: 7.5, reasoning: 8.5, speed: 8.5, vision: 8.0, creative: 8.5, value: 8.0 },
    ratingReasons: {
      coding: 'Grok 4 shows strong coding ability, competitive with GPT-4o on benchmarks',
      writing: 'Decent writing with a distinctive unfiltered personality and style',
      reasoning: 'Grok 4 demonstrates strong logical reasoning and problem-solving',
      speed: 'Fast inference with streaming; responsive for most query types',
      vision: 'Capable image understanding plus Aurora for image generation',
      creative: 'Unfiltered approach allows more creative freedom than competitors',
      value: 'Premium AI access from just $8/mo via X Premium is a bargain'
    },
    topUseCases: ['Getting real-time insights on trending X/Twitter topics', 'Generating unfiltered creative content and images with Aurora', 'Affordable daily AI assistance via X Premium'],
    pros: ['Grok 4 — strong reasoning & search', 'Real-time X/Twitter data', 'Less filtered than competitors', 'Aurora image generation', 'Cheapest premium AI ($8/mo)'],
    cons: ['Tied to X/Twitter ecosystem', 'Smaller context than Claude/Gemini', 'Less polished interface', 'Limited third-party integrations'],
    bestFor: 'Social media, trending topics & unfiltered AI',
    simpleDesc: 'xAI\'s fast-growing assistant, built into X/Twitter. Less filtered, with real-time access to social data. Grok 4 made it competitive with the best.',
    whoFor: 'X/Twitter users, people who want unfiltered AI, trend watchers',
    url: 'https://grok.x.ai'
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    maker: 'Perplexity AI',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/perplexity/ffffff',
    color: '#20b2aa',
    colorRgb: '32,178,170',
    tagline: 'The answer engine',
    model: 'Sonar, Claude, GPT-4o (multi-model)',
    launched: '2022',
    users: '100M+ monthly users',
    pricing: { free: 'Free (5 Pro/day)', pro: '$20/mo (Pro)', top: '$40/mo (Enterprise)' },
    ratings: { coding: 6.5, writing: 7.5, reasoning: 8.0, speed: 9.0, vision: 6.5, creative: 6.0, value: 9.0 },
    ratingReasons: {
      coding: 'Limited coding ability; designed for research, not development tasks',
      writing: 'Clean, well-structured answers but not suited for creative or long-form writing',
      reasoning: 'Multi-model approach with strong analytical and research reasoning',
      speed: 'Very fast search-and-answer pipeline with real-time web access',
      vision: 'Basic image understanding; no image generation capabilities',
      creative: 'Focused on factual accuracy over creative output',
      value: 'Generous free tier with 5 Pro searches/day; Pro at $20/mo is solid'
    },
    topUseCases: ['Researching topics with cited, verifiable sources', 'Getting up-to-date answers with real-time web search', 'Fact-checking claims and comparing information across sources'],
    pros: ['Always cites sources — verify anything', 'Real-time web search built in', 'Uses multiple models under the hood', 'Clean, distraction-free UI', 'Excellent for research'],
    cons: ['Weak at creative writing', 'Limited coding help', 'Not great for long conversations', 'Can\'t generate images'],
    bestFor: 'Research & sourced answers',
    simpleDesc: 'A smarter Google. Ask any question, get a clear answer with sources linked. The go-to tool for research and fact-checking.',
    whoFor: 'Researchers, journalists, students, anyone who wants verified answers',
    url: 'https://perplexity.ai'
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    maker: 'DeepSeek AI',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/deepseek/ffffff',
    color: '#4d6bfe',
    colorRgb: '77,107,254',
    tagline: 'China\'s open-source challenger',
    model: 'DeepSeek-V3, DeepSeek-R1',
    launched: '2024',
    users: 'Viral growth, top 10 globally',
    pricing: { free: 'Free (web)', pro: 'API: ultra-cheap', top: 'Self-host (open source)' },
    ratings: { coding: 8.5, writing: 7.5, reasoning: 9.0, speed: 8.0, vision: 6.0, creative: 7.0, value: 9.5 },
    ratingReasons: {
      coding: 'V3 matches GPT-4o on coding benchmarks at a fraction of the cost',
      writing: 'Competent English writing but noticeably weaker than Claude or GPT-4o',
      reasoning: 'R1 reasoning model rivals OpenAI o1 on maths and logic benchmarks',
      speed: 'Good response times though can slow down during peak usage',
      vision: 'Limited multimodal capabilities compared to Western competitors',
      creative: 'Decent creative output but not a standout in this category',
      value: 'Free web access and the cheapest API in the industry — unbeatable value'
    },
    topUseCases: ['Complex maths and logic problem-solving with R1', 'Budget-friendly API access for AI-powered applications', 'Self-hosting an open-source model for full data privacy'],
    pros: ['R1 reasoning rivals o1/o3', 'Extremely cheap API pricing', 'Open source — run it yourself', 'Strong at maths and coding', 'Free web access'],
    cons: ['Chinese company — data concerns', 'English writing weaker than Claude', 'Limited multimodal abilities', 'Web interface basic'],
    bestFor: 'Cheap, powerful reasoning & open-source AI',
    simpleDesc: 'A Chinese AI lab that shocked the industry with models rivalling OpenAI at a fraction of the cost. Free to use and open source.',
    whoFor: 'Budget-conscious users, developers, privacy advocates who self-host',
    url: 'https://chat.deepseek.com'
  },
  {
    id: 'characterai',
    name: 'Character.AI',
    maker: 'Character Technologies',
    category: 'assistant',
    logo: 'https://characterai.io/favicon.ico',
    color: '#8b5cf6',
    colorRgb: '139,92,246',
    tagline: 'Talk to anyone — real or imagined',
    model: 'Custom character models',
    launched: '2022',
    users: '#3 AI on web, 298 sessions/user/month',
    pricing: { free: 'Free (generous)', pro: '$9.99/mo (c.ai+)', top: 'N/A' },
    ratings: { coding: 3.0, writing: 7.0, reasoning: 5.0, speed: 9.0, vision: 3.0, creative: 9.0, value: 9.0 },
    ratingReasons: {
      coding: 'Not designed for coding; character models lack technical capability',
      writing: 'Engaging conversational writing with strong character voice consistency',
      reasoning: 'Limited analytical reasoning; optimised for conversation, not problem-solving',
      speed: 'Extremely fast responses enabling real-time conversational flow',
      vision: 'Minimal image capabilities; text-based conversation focused',
      creative: 'Exceptional at roleplay, storytelling, and creative conversation',
      value: 'Generous free tier with c.ai+ at $9.99/mo for premium features'
    },
    topUseCases: ['Engaging roleplay with fictional or historical characters', 'Practising conversations and language learning', 'Creative storytelling and interactive fiction'],
    pros: ['Incredibly engaging conversations', 'Millions of characters to talk to', 'Create your own characters', 'Most addictive AI product', 'Great for roleplay & creativity'],
    cons: ['Not for professional work', 'Hallucinations common', 'No web browsing', 'Content filters can be aggressive'],
    bestFor: 'Entertainment, roleplay & AI companionship',
    simpleDesc: 'Chat with AI versions of anyone — fictional characters, celebrities, or custom personalities. The most engaging and addictive AI chat experience.',
    whoFor: 'People wanting entertainment, creative roleplay, or AI companionship',
    url: 'https://character.ai'
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    maker: 'Microsoft',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/microsoft/ffffff',
    color: '#0078d4',
    colorRgb: '0,120,212',
    tagline: 'AI built into Windows and Office',
    model: 'GPT-4o',
    launched: '2023',
    users: '100M+ users',
    pricing: { free: 'Free (very generous)', pro: '$20/mo (Pro)', top: '$30/user/mo (M365)' },
    ratings: { coding: 7.0, writing: 7.5, reasoning: 7.5, speed: 8.5, vision: 7.5, creative: 7.0, value: 9.5 },
    ratingReasons: {
      coding: 'Can write and explain code via GPT-4o but not a dedicated dev tool',
      writing: 'Strong writing assistance integrated into Word, Outlook, and Edge',
      reasoning: 'GPT-4o powered analysis with web search for grounded answers',
      speed: 'Fast responses with deep OS-level integration across Windows',
      vision: 'Image understanding plus DALL-E 3 generation included free',
      creative: 'Solid creative features with Designer image tool built in',
      value: 'Extremely generous free tier — GPT-4o access without paying anything'
    },
    topUseCases: ['AI-powered writing and editing in Microsoft Office apps', 'Quick web searches with AI-summarised answers in Edge', 'Generating images and creative content for free with Designer'],
    pros: ['Built into Windows, Edge, and Office', 'GPT-4o access completely free', 'DALL-E 3 image generation included', 'Deep Microsoft 365 integration', 'Designer for AI graphics'],
    cons: ['Less capable than ChatGPT for complex tasks', 'Microsoft ecosystem focus', 'Pro features require M365 subscription', 'Can feel generic compared to specialised tools'],
    bestFor: 'Free AI for Windows and Office users',
    simpleDesc: 'Microsoft\'s AI assistant built into Windows, Edge, and Office 365. Uses GPT-4o with generous free access, image generation, and deep productivity integration.',
    whoFor: 'Windows users, Office 365 subscribers, anyone wanting free GPT-4o access',
    url: 'https://copilot.microsoft.com'
  },

  // === CODING & APP BUILDING ===
  {
    id: 'cursor',
    name: 'Cursor',
    maker: 'Cursor Inc',
    category: 'coding',
    logo: 'https://www.cursor.com/favicon.ico',
    color: '#7c3aed',
    colorRgb: '124,58,237',
    tagline: 'The AI code editor',
    model: 'Claude, GPT-4o, custom (multi-model)',
    launched: '2023',
    users: 'Top developer tool',
    pricing: { free: 'Free (limited)', pro: '$20/mo (Pro)', top: '$40/mo (Business)' },
    ratings: { coding: 9.5, writing: 5.0, reasoning: 8.5, speed: 8.5, vision: 6.0, creative: 5.5, value: 8.5 },
    ratingReasons: {
      coding: 'Best-in-class AI code editor with codebase-aware multi-file editing',
      writing: 'Code-focused tool; not designed for general writing tasks',
      reasoning: 'Strong code reasoning through multi-model support including Claude and GPT-4o',
      speed: 'Fast tab completions and inline suggestions; responsive editing experience',
      vision: 'Can reference images for UI work but limited compared to general AI',
      creative: 'Focused on code generation rather than creative tasks',
      value: 'Pro at $20/mo is excellent for developers who code daily'
    },
    topUseCases: ['Refactoring and editing code across multiple files simultaneously', 'Understanding and navigating large unfamiliar codebases', 'AI-powered tab completion that predicts your next edit'],
    pros: ['Best AI coding experience available', 'Understands your entire codebase', 'Multi-file editing in one go', 'Supports multiple AI models', 'Tab-complete that reads your mind'],
    cons: ['Code-only — not general purpose', 'Can burn through API credits fast', 'Learning curve for full potential', 'VS Code fork — some extensions break'],
    bestFor: 'Professional software development',
    simpleDesc: 'A code editor supercharged with AI. Understands your whole project and writes, edits, and debugs code across files. The tool pro developers love.',
    whoFor: 'Software developers who want to code much faster',
    url: 'https://cursor.com'
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    maker: 'GitHub / Microsoft',
    category: 'coding',
    logo: 'https://cdn.simpleicons.org/github/ffffff',
    color: '#238636',
    colorRgb: '35,134,54',
    tagline: 'The original AI pair programmer',
    model: 'GPT-4o, Claude (multi-model)',
    launched: '2021',
    users: 'Millions of developers',
    pricing: { free: 'Free (limited)', pro: '$10/mo (Individual)', top: '$19/mo (Business)' },
    ratings: { coding: 9.0, writing: 4.0, reasoning: 7.0, speed: 9.0, vision: 4.0, creative: 4.0, value: 9.0 },
    ratingReasons: {
      coding: 'The original AI coding assistant with deep IDE integration and multi-model support',
      writing: 'Designed for code, not prose — minimal general writing capability',
      reasoning: 'GPT-4o and Claude power solid code reasoning and understanding',
      speed: 'Inline suggestions appear in milliseconds; extremely responsive',
      vision: 'Limited visual capabilities; primarily text-based code assistance',
      creative: 'Focused on code completion, not creative tasks',
      value: '$10/mo Individual with unlimited completions is outstanding value for devs'
    },
    topUseCases: ['Inline code completions and suggestions in your IDE', 'Generating functions and boilerplate from natural language comments', 'Understanding and explaining unfamiliar code in any language'],
    pros: ['The most widely used AI coding tool', 'Works in VS Code, JetBrains, Neovim', 'Multi-model with GPT-4o and Claude', 'GitHub ecosystem integration', 'Agent mode for multi-file tasks'],
    cons: ['Less capable than Cursor for complex edits', 'No full-app generation', 'Suggestions can be repetitive', 'Requires IDE — no web interface'],
    bestFor: 'AI-powered code completion in your IDE',
    simpleDesc: 'The original AI pair programmer used by millions of developers. Suggests code as you type, generates functions from comments, and works across all major IDEs.',
    whoFor: 'Developers wanting AI assistance directly in their editor',
    url: 'https://github.com/features/copilot'
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    maker: 'Codeium',
    category: 'coding',
    logo: 'https://windsurf.com/favicon.ico',
    color: '#00c896',
    colorRgb: '0,200,150',
    tagline: 'Agentic AI code editor',
    model: 'Multi-model (Claude, GPT-4o, custom)',
    launched: '2024',
    users: 'Fast-growing developer tool',
    pricing: { free: 'Free (limited)', pro: '$10/mo (Pro)', top: '$30/mo (Team)' },
    ratings: { coding: 9.0, writing: 4.5, reasoning: 8.0, speed: 8.5, vision: 5.0, creative: 5.0, value: 9.0 },
    ratingReasons: {
      coding: 'Cascade agentic flows enable multi-step code changes across files',
      writing: 'Coding-focused tool with minimal general writing capability',
      reasoning: 'Multi-model reasoning with strong codebase-wide understanding',
      speed: 'Fast completions with efficient multi-file editing workflows',
      vision: 'Limited visual capabilities; primarily code-focused',
      creative: 'Focused on software engineering, not creative tasks',
      value: '$10/mo is half the price of Cursor with comparable coding features'
    },
    topUseCases: ['Agentic multi-file code editing with Cascade flows', 'Codebase-wide refactoring and feature implementation', 'Affordable AI-powered coding alternative to Cursor'],
    pros: ['Cascade agentic coding flows', 'Half the price of Cursor', 'Strong codebase understanding', 'Multi-model support', 'Fast iteration and editing'],
    cons: ['Newer than Cursor — smaller community', 'Some features still maturing', 'Plugin ecosystem limited', 'Less brand recognition'],
    bestFor: 'Affordable agentic AI coding',
    simpleDesc: 'Cursor\'s main competitor with unique Cascade agentic flows for multi-step coding tasks. Strong codebase understanding at half the price.',
    whoFor: 'Developers wanting Cursor-level AI coding at a lower price',
    url: 'https://windsurf.com'
  },
  {
    id: 'replit',
    name: 'Replit',
    maker: 'Replit',
    category: 'coding',
    logo: 'https://cdn.simpleicons.org/replit/ffffff',
    color: '#f26522',
    colorRgb: '242,101,34',
    tagline: 'Describe it. Deploy it.',
    model: 'Replit Agent (multi-model)',
    launched: '2024',
    users: 'Top 50 AI web product (a16z)',
    pricing: { free: 'Free (limited)', pro: '$25/mo (Core)', top: '$40/mo (Teams)' },
    ratings: { coding: 8.5, writing: 4.5, reasoning: 7.0, speed: 8.0, vision: 4.0, creative: 5.0, value: 8.0 },
    ratingReasons: {
      coding: 'Full-stack app generation from prompts with instant deployment',
      writing: 'Not designed for writing; coding and app building focused',
      reasoning: 'Agent handles planning and architecture for app generation',
      speed: 'Fast prototyping with browser-based dev environment',
      vision: 'Limited visual capabilities; text-to-app focused',
      creative: 'Good for creative app ideas but output is functional, not artistic',
      value: 'Free tier available; $25/mo Core includes hosting and deployment'
    },
    topUseCases: ['Building and deploying a full-stack web app from a description', 'Rapid prototyping of startup MVPs and side projects', 'Collaborative coding with built-in hosting and databases'],
    pros: ['Describe an app → get a working app', 'Instant deployment included', 'Full dev environment in browser', 'Handles backend + frontend + database', 'Great for prototyping fast'],
    cons: ['Less control than local dev', 'Credit system can get expensive', 'Complex apps can be hit-or-miss', 'Limited to web apps'],
    bestFor: 'Building and deploying apps from scratch',
    simpleDesc: 'Tell it what app you want, and it builds the whole thing — frontend, backend, database, and hosting. Ideal for turning ideas into live products.',
    whoFor: 'Entrepreneurs, indie hackers, anyone who wants to ship apps fast',
    url: 'https://replit.com'
  },
  {
    id: 'lovable',
    name: 'Lovable',
    maker: 'Lovable',
    category: 'coding',
    logo: 'https://lovable.dev/favicon.ico',
    color: '#e040fb',
    colorRgb: '224,64,251',
    tagline: 'Vibe code beautiful apps',
    model: 'Claude-powered',
    launched: '2024',
    users: '#22 AI web product (a16z)',
    pricing: { free: 'Free (limited)', pro: '$20/mo (Launch)', top: '$100/mo (Scale)' },
    ratings: { coding: 8.0, writing: 4.0, reasoning: 6.5, speed: 8.5, vision: 7.5, creative: 7.5, value: 7.5 },
    ratingReasons: {
      coding: 'Generates polished React + Tailwind apps with beautiful default designs',
      writing: 'Not a writing tool; focused on code and app generation',
      reasoning: 'Claude-powered reasoning for app architecture decisions',
      speed: 'Very fast iteration cycles for web app generation',
      vision: 'Produces visually polished UIs; good design sense built in',
      creative: 'Strong aesthetic sense with beautiful default styling',
      value: 'Launch tier at $20/mo is fair for the quality of generated apps'
    },
    topUseCases: ['Creating polished web apps without coding knowledge', 'Building landing pages and marketing sites quickly', 'Prototyping SaaS products with Supabase backend integration'],
    pros: ['Beautiful UI designs by default', 'Supabase backend integration', 'GitHub sync built in', 'Very fast iteration', 'No coding knowledge needed'],
    cons: ['React + Tailwind only', 'Complex logic can struggle', 'Newer platform — still maturing', 'Limited customisation depth'],
    bestFor: 'Beautiful web apps without coding',
    simpleDesc: 'Describe the app you want, get a polished web app with modern design. Syncs with GitHub and integrates databases automatically.',
    whoFor: 'Non-technical creators who want professional-looking apps',
    url: 'https://lovable.dev'
  },
  {
    id: 'bolt',
    name: 'Bolt',
    maker: 'StackBlitz',
    category: 'coding',
    logo: 'https://bolt.new/favicon.ico',
    color: '#ff6b00',
    colorRgb: '255,107,0',
    tagline: 'Prompt. Run. Ship.',
    model: 'Multi-model (Claude, GPT-4o)',
    launched: '2024',
    users: 'a16z Top 100 AI product',
    pricing: { free: 'Free (limited)', pro: '$20/mo', top: '$40/mo (Team)' },
    ratings: { coding: 8.0, writing: 4.0, reasoning: 6.5, speed: 9.0, vision: 5.0, creative: 6.0, value: 8.0 },
    ratingReasons: {
      coding: 'Full-stack code generation running entirely in the browser via WebContainers',
      writing: 'Not designed for writing tasks; purely a coding tool',
      reasoning: 'Multi-model reasoning for app architecture and code generation',
      speed: 'Instant in-browser execution — fastest prototype-to-running-app experience',
      vision: 'Basic visual output for generated apps; not image-focused',
      creative: 'Functional app generation focused on utility over aesthetics',
      value: '$20/mo with browser-based convenience is good value for prototyping'
    },
    topUseCases: ['Instant full-stack app prototyping in the browser', 'Generating working demos without local dev setup', 'Quick iteration on web app ideas with multiple AI models'],
    pros: ['Runs code entirely in-browser', 'No setup or deployment needed', 'WebContainer technology = instant', 'Full-stack app generation', 'Multiple model choices'],
    cons: ['Complex apps can be inconsistent', 'Browser-based limitations', 'Newer than Replit/Lovable', 'Less design polish than Lovable'],
    bestFor: 'Instant full-stack prototypes',
    simpleDesc: 'Type a prompt and get a running full-stack app instantly in your browser. No setup, no deployment — it just works.',
    whoFor: 'Developers wanting instant prototypes, vibe coders',
    url: 'https://bolt.new'
  },
  {
    id: 'v0',
    name: 'v0',
    maker: 'Vercel',
    category: 'coding',
    logo: 'https://cdn.simpleicons.org/vercel/ffffff',
    color: '#000000',
    colorRgb: '100,100,100',
    tagline: 'Generate UI with AI',
    model: 'Multi-model',
    launched: '2024',
    users: 'Growing rapidly',
    pricing: { free: 'Free (limited)', pro: '$20/mo (Premium)', top: '$30/mo (Team)' },
    ratings: { coding: 8.0, writing: 3.5, reasoning: 6.0, speed: 8.0, vision: 7.0, creative: 7.5, value: 7.5 },
    ratingReasons: {
      coding: 'Excellent React/Next.js component generation with production-ready code',
      writing: 'Not a writing tool; specialised for UI code generation',
      reasoning: 'Good at understanding UI requirements and component architecture',
      speed: 'Fast component generation with instant preview',
      vision: 'Strong visual output — generates beautiful UI components',
      creative: 'High aesthetic quality with shadcn/ui and modern design patterns',
      value: '$20/mo Premium is fair for frontend developers who use it regularly'
    },
    topUseCases: ['Generating React UI components from text descriptions', 'Building shadcn/ui based interfaces for Next.js projects', 'Rapid frontend prototyping with one-click Vercel deploy'],
    pros: ['Beautiful component generation', 'React/Next.js/Tailwind native', 'One-click deploy to Vercel', 'Great shadcn/ui integration', 'Excellent for UI components'],
    cons: ['Frontend-focused only', 'Limited backend generation', 'Vercel ecosystem lock-in', 'Not for full app generation'],
    bestFor: 'Generating UI components and frontends',
    simpleDesc: 'Generate beautiful React UI components from text descriptions. Produces clean, production-ready code using modern frameworks.',
    whoFor: 'Frontend developers, designers who code, React developers',
    url: 'https://v0.dev'
  },
  {
    id: 'devin',
    name: 'Devin',
    maker: 'Cognition',
    category: 'coding',
    logo: 'https://devin.ai/favicon.ico',
    color: '#00d4aa',
    colorRgb: '0,212,170',
    tagline: 'The AI software engineer',
    model: 'Devin (proprietary)',
    launched: '2024',
    users: 'Enterprise early access',
    pricing: { free: 'No', pro: '$500/mo', top: 'Enterprise (custom)' },
    ratings: { coding: 9.0, writing: 4.0, reasoning: 8.5, speed: 5.5, vision: 5.0, creative: 4.5, value: 4.0 },
    ratingReasons: {
      coding: 'Truly autonomous software engineering with own browser, terminal, and editor',
      writing: 'Not designed for writing; focused on software engineering tasks',
      reasoning: 'Strong multi-step reasoning for complex development workflows',
      speed: 'Slow for simple tasks — designed for complex multi-hour projects',
      vision: 'Can use a browser for visual testing but limited image capabilities',
      creative: 'Functional engineering output; not suited for creative tasks',
      value: 'At $500/mo it is expensive and only worth it for heavy engineering teams'
    },
    topUseCases: ['Automating routine development tasks like bug fixes and migrations', 'Building features autonomously from GitHub issue descriptions', 'Learning and working across unfamiliar codebases independently'],
    pros: ['Truly autonomous — works independently', 'Own browser, terminal & editor', 'Can learn entire codebases', 'Handles multi-step projects', 'Replaces junior dev tasks'],
    cons: ['$500/month — very expensive', 'Slow for simple tasks', 'Quality varies on complex work', 'Overkill for most use cases'],
    bestFor: 'Autonomous development tasks',
    simpleDesc: 'An AI that works like a junior software developer. Give it a task and it plans, codes, tests, and deploys independently over hours.',
    whoFor: 'Engineering teams wanting to automate routine development',
    url: 'https://devin.ai'
  },

  // === IMAGE GENERATION ===
  {
    id: 'midjourney',
    name: 'Midjourney',
    maker: 'Midjourney Inc',
    category: 'image',
    logo: 'https://cdn.simpleicons.org/midjourney/ffffff',
    color: '#ff6b35',
    colorRgb: '255,107,53',
    tagline: 'The AI artist',
    model: 'Midjourney v6.1',
    launched: '2022',
    users: 'a16z All-Star (every list)',
    pricing: { free: 'No free tier', pro: '$10/mo (Basic)', top: '$60/mo (Mega)' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 7.5, vision: 9.5, creative: 9.5, value: 8.0 },
    ratingReasons: {
      coding: 'Not a coding tool; specialised purely in image generation',
      writing: 'No text generation capabilities; image-only tool',
      reasoning: 'No analytical reasoning; interprets prompts for visual output',
      speed: 'Generation takes 30-60 seconds; fast enough for creative workflows',
      vision: 'Produces the most aesthetically stunning AI images available',
      creative: 'Gold standard for AI art with unmatched style and composition',
      value: 'Starting at $10/mo with excellent quality makes it solid value'
    },
    topUseCases: ['Creating marketing and branding visuals with stunning aesthetics', 'Generating concept art and mood boards for creative projects', 'Producing photorealistic product mockups and lifestyle imagery'],
    pros: ['Stunning artistic image quality', 'Consistent style and aesthetics', 'Great for branding & marketing', 'Active creative community', 'Photorealistic capability'],
    cons: ['No free tier', 'Mostly Discord-based', 'Cannot do text or code', 'Prompt crafting learning curve'],
    bestFor: 'Beautiful AI-generated images',
    simpleDesc: 'Creates stunning AI images from text descriptions. The gold standard for artistic, marketing, and design visuals.',
    whoFor: 'Designers, marketers, content creators, artists',
    url: 'https://midjourney.com'
  },
  {
    id: 'leonardo',
    name: 'Leonardo.AI',
    maker: 'Leonardo AI',
    category: 'image',
    logo: 'https://leonardo.ai/favicon.ico',
    color: '#9333ea',
    colorRgb: '147,51,234',
    tagline: 'Creative AI for everyone',
    model: 'Phoenix, Flux, SDXL',
    launched: '2023',
    users: 'a16z All-Star (every list)',
    pricing: { free: '150 tokens/day free', pro: '$10/mo', top: '$48/mo' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 8.0, vision: 9.0, creative: 9.0, value: 8.5 },
    ratingReasons: {
      coding: 'Not a coding tool; focused on image generation and editing',
      writing: 'No text generation; purely visual creative tool',
      reasoning: 'No analytical reasoning; prompt-to-image focused',
      speed: 'Fast generation with multiple model options and real-time canvas',
      vision: 'Excellent image quality across multiple models including Phoenix and Flux',
      creative: 'Versatile creative tool with strong game art and concept art capabilities',
      value: 'Generous free tier of 150 tokens/day; Pro at $10/mo is great value'
    },
    topUseCases: ['Creating game assets and concept art with multiple AI models', 'Real-time image editing and variations on a visual canvas', 'Generating free AI art with a generous daily token allowance'],
    pros: ['Generous free tier', 'Multiple model choices', 'Real-time canvas editing', 'Great for game & concept art', 'Web-based (no Discord needed)'],
    cons: ['Less consistent than Midjourney', 'Token system can be confusing', 'Learning curve for best results', 'Photorealism slightly behind'],
    bestFor: 'Accessible AI image creation',
    simpleDesc: 'A web-based AI art studio with multiple models, a free tier, and real-time editing. More accessible than Midjourney with similar quality.',
    whoFor: 'Digital artists, game developers, anyone wanting free AI images',
    url: 'https://leonardo.ai'
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    maker: 'Ideogram',
    category: 'image',
    logo: 'https://ideogram.ai/favicon.ico',
    color: '#8e44ef',
    colorRgb: '142,68,239',
    tagline: 'Perfect text in every image',
    model: 'Ideogram 2.0',
    launched: '2023',
    users: 'Fast-growing, trending on social media',
    pricing: { free: 'Free tier (generous)', pro: '$8/mo (Basic)', top: '$20/mo (Plus)' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 7.5, vision: 9.0, creative: 9.0, value: 8.5 },
    ratingReasons: {
      coding: 'Not a coding tool; image generation focused',
      writing: 'No text generation; visual creative tool',
      reasoning: 'No analytical reasoning; image generation only',
      speed: 'Reasonably fast generation with batch output options',
      vision: 'Exceptional image quality with the best text-in-image rendering available',
      creative: 'Highly creative output with strong typography and design aesthetics',
      value: 'Generous free tier with daily generations; affordable paid plans'
    },
    topUseCases: ['Creating logos and designs with perfect text rendering', 'Generating social media graphics with embedded typography', 'Producing marketing visuals that require readable text in images'],
    pros: ['Best text-in-image accuracy', 'Generous free tier', 'Trending quality improvements', 'Strong logo/typography generation', 'Web-based and accessible'],
    cons: ['Newer platform — smaller community', 'Less artistic range than Midjourney', 'Limited editing tools', 'API access limited'],
    bestFor: 'AI images with perfect text and typography',
    simpleDesc: 'The best AI image generator for text in images. Creates stunning visuals with perfect typography, logos, and readable text.',
    whoFor: 'Designers, marketers, anyone needing text-heavy graphics',
    url: 'https://ideogram.ai'
  },
  {
    id: 'firefly',
    name: 'Adobe Firefly',
    maker: 'Adobe',
    category: 'image',
    logo: 'https://cdn.simpleicons.org/adobe/ffffff',
    color: '#ff6b2b',
    colorRgb: '255,107,43',
    tagline: 'Commercially safe AI images',
    model: 'Firefly Image 3',
    launched: '2023',
    users: 'Integrated into Adobe\'s 30M+ Creative Cloud users',
    pricing: { free: '25 credits/mo free', pro: '$5/mo (standalone)', top: 'Included in Creative Cloud' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 7.5, vision: 8.5, creative: 8.5, value: 7.0 },
    ratingReasons: {
      coding: 'Not a coding tool; image generation and editing focused',
      writing: 'No text generation; visual creative tool',
      reasoning: 'No analytical reasoning; image generation only',
      speed: 'Fast generation integrated directly into Photoshop and Express',
      vision: 'High-quality image generation with strong editing and compositing',
      creative: 'Commercially safe AI images trained on licensed Adobe Stock content',
      value: '$5/mo standalone or included with Creative Cloud subscription'
    },
    topUseCases: ['Generating commercially safe AI images for professional use', 'Using Generative Fill and Expand in Adobe Photoshop', 'Creating design variations and mockups in Adobe Express'],
    pros: ['Commercially safe — trained on licensed content', 'Deep Photoshop integration', 'Generative Fill and Expand', 'Professional-grade output', 'Adobe ecosystem seamless'],
    cons: ['Less creative range than Midjourney', 'Credit-based pricing', 'Requires Adobe ecosystem for full power', 'Free tier is limited'],
    bestFor: 'Commercially safe AI images for pros',
    simpleDesc: 'Adobe\'s AI image generator, integrated into Photoshop and Creative Cloud. Trained on licensed content for commercially safe output.',
    whoFor: 'Professional designers, photographers, Creative Cloud users',
    url: 'https://firefly.adobe.com'
  },

  // === VIDEO ===
  {
    id: 'runway',
    name: 'Runway',
    maker: 'Runway',
    category: 'video',
    logo: 'https://runwayml.com/favicon.ico',
    color: '#00c2ff',
    colorRgb: '0,194,255',
    tagline: 'The AI video studio',
    model: 'Gen-3 Alpha Turbo',
    launched: '2023',
    users: 'Leading AI video tool',
    pricing: { free: '125 credits free', pro: '$12/mo', top: '$76/mo (Unlimited)' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 7.0, vision: 9.0, creative: 9.0, value: 7.0 },
    ratingReasons: {
      coding: 'Not a coding tool; focused on video generation and editing',
      writing: 'No text generation; video production focused',
      reasoning: 'No analytical reasoning; creative video tool',
      speed: 'Video generation takes minutes; reasonable for the medium',
      vision: 'Gen-3 Alpha produces high-quality video with strong visual fidelity',
      creative: 'Industry-leading AI video with motion brush and cinematic output',
      value: 'Credits deplete fast for heavy use; $12/mo entry is reasonable'
    },
    topUseCases: ['Generating short AI video clips from text or image prompts', 'Adding motion to still images for social media content', 'Professional video editing with AI-powered tools'],
    pros: ['Best-in-class AI video generation', 'Text-to-video and image-to-video', 'Professional editing tools', 'Motion brush control', 'Used by Hollywood studios'],
    cons: ['Credits used up quickly', 'Short clips (5-10 seconds)', 'Expensive for heavy use', 'Faces can be uncanny'],
    bestFor: 'AI video generation and editing',
    simpleDesc: 'Create short AI videos from text or images. Used by filmmakers and marketers. The most established AI video tool.',
    whoFor: 'Video creators, filmmakers, marketers, social media managers',
    url: 'https://runwayml.com'
  },
  {
    id: 'sora',
    name: 'Sora',
    maker: 'OpenAI',
    category: 'video',
    logo: 'https://cdn.simpleicons.org/openai/ffffff',
    color: '#10a37f',
    colorRgb: '16,163,127',
    tagline: 'OpenAI\'s video model',
    model: 'Sora',
    launched: '2024',
    users: 'Available via ChatGPT Pro',
    pricing: { free: 'No (ChatGPT Plus needed)', pro: '$20/mo (via Plus)', top: '$200/mo (via Pro)' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 6.0, vision: 9.5, creative: 9.0, value: 6.0 },
    ratingReasons: {
      coding: 'Not a coding tool; OpenAI\'s dedicated video generation model',
      writing: 'No text generation; video-only tool',
      reasoning: 'No analytical reasoning; video generation focused',
      speed: 'Slow generation times with limited monthly quota',
      vision: 'Produces the most realistic AI video with strong physics understanding',
      creative: 'Exceptional cinematic quality with storyboard and remix modes',
      value: 'Requires ChatGPT Plus ($20/mo minimum) with very limited generations'
    },
    topUseCases: ['Creating cinematic AI video clips with realistic physics', 'Storyboarding and visualising creative video concepts', 'Generating premium video content for marketing campaigns'],
    pros: ['Incredible visual quality', 'Longer clips than competitors', 'Physics understanding', 'Text-to-video & image-to-video', 'Storyboard mode'],
    cons: ['Only via ChatGPT subscription', 'Slow generation times', 'Very limited monthly generations', 'Content policy restrictions'],
    bestFor: 'Highest quality AI video',
    simpleDesc: 'OpenAI\'s video generator creates stunningly realistic short videos. Limited access but the highest quality AI video available.',
    whoFor: 'Filmmakers, marketers wanting premium AI video',
    url: 'https://sora.com'
  },
  {
    id: 'pika',
    name: 'Pika',
    maker: 'Pika Labs',
    category: 'video',
    logo: 'https://pika.art/favicon.ico',
    color: '#a855f7',
    colorRgb: '168,85,247',
    tagline: 'Fun AI video creation',
    model: 'Pika 2.0',
    launched: '2023',
    users: 'Millions of creators',
    pricing: { free: 'Free tier available', pro: '$8/mo (Standard)', top: '$58/mo (Unlimited)' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 7.5, vision: 8.5, creative: 8.5, value: 7.5 },
    ratingReasons: {
      coding: 'Not a coding tool; video generation focused',
      writing: 'No text generation; video creation tool',
      reasoning: 'No analytical reasoning; creative video tool',
      speed: 'Fast video generation compared to competitors like Sora',
      vision: 'Good quality video output with text-to-video and image-to-video',
      creative: 'Strong creative video generation with fun effects and styles',
      value: '$8/mo starter plan is affordable for casual video creation'
    },
    topUseCases: ['Generating short AI videos from text prompts', 'Animating still photos and images into video clips', 'Creating social media video content quickly'],
    pros: ['Easy-to-use interface', 'Fun creative effects', 'Affordable pricing', 'Text and image to video', 'Fast generation times'],
    cons: ['Lower quality than Runway/Sora', 'Short clip lengths', 'Limited fine control', 'Faces can be inconsistent'],
    bestFor: 'Quick, affordable AI video creation',
    simpleDesc: 'A fun and accessible AI video generator. Turn text or images into short videos with creative effects. More affordable than Runway.',
    whoFor: 'Social media creators, casual video makers, content creators',
    url: 'https://pika.art'
  },
  {
    id: 'kling',
    name: 'Kling AI',
    maker: 'Kuaishou',
    category: 'video',
    logo: 'https://klingai.com/favicon.ico',
    color: '#0066ff',
    colorRgb: '0,102,255',
    tagline: 'Cinematic AI video',
    model: 'Kling 1.6',
    launched: '2024',
    users: 'Viral growth globally',
    pricing: { free: 'Free tier (66 credits/day)', pro: '$5.99/mo (Standard)', top: '$30/mo (Pro)' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 6.5, vision: 9.0, creative: 9.0, value: 8.0 },
    ratingReasons: {
      coding: 'Not a coding tool; video generation focused',
      writing: 'No text generation; video creation tool',
      reasoning: 'No analytical reasoning; creative video tool',
      speed: 'Slower generation but produces longer, more detailed clips',
      vision: 'Stunning cinematic video quality rivalling Runway and Sora',
      creative: 'Exceptional cinematic style with photorealistic motion and scenes',
      value: 'Generous free tier with daily credits; best free video generation'
    },
    topUseCases: ['Creating cinematic AI video clips with photorealistic quality', 'Generating viral-quality short-form video content', 'Producing product demos and marketing videos with AI'],
    pros: ['Stunning cinematic quality', 'Generous free tier', 'Long clip generation', 'Excellent motion quality', 'Photorealistic output'],
    cons: ['Chinese platform — data concerns', 'Slower than competitors', 'English interface rough', 'Limited editing tools'],
    bestFor: 'Free cinematic AI video generation',
    simpleDesc: 'A Chinese AI video generator that went viral for its cinematic quality. Produces photorealistic video clips with generous free access.',
    whoFor: 'Content creators, filmmakers wanting free high-quality AI video',
    url: 'https://klingai.com'
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    maker: 'HeyGen',
    category: 'video',
    logo: 'https://heygen.com/favicon.ico',
    color: '#5046e4',
    colorRgb: '80,70,228',
    tagline: 'AI avatar videos for business',
    model: 'HeyGen Avatar Engine',
    launched: '2023',
    users: 'Enterprise favourite, 40K+ businesses',
    pricing: { free: 'Free trial', pro: '$24/mo (Creator)', top: '$120/mo (Business)' },
    ratings: { coding: 1.0, writing: 3.0, reasoning: 2.0, speed: 7.0, vision: 8.0, creative: 7.5, value: 6.0 },
    ratingReasons: {
      coding: 'Not a coding tool; AI avatar video focused',
      writing: 'Script-to-video capability with multilingual translation',
      reasoning: 'No analytical reasoning; video production tool',
      speed: 'Fast avatar video generation once set up; batch processing available',
      vision: 'Realistic AI avatars with lip sync and natural gestures',
      creative: 'Good for professional video but less artistic than Runway or Kling',
      value: '$24/mo is pricey for individuals but reasonable for business use'
    },
    topUseCases: ['Creating AI avatar videos for training and onboarding', 'Translating video content into 40+ languages with lip sync', 'Producing professional talking-head videos without a camera'],
    pros: ['Realistic AI avatar generation', 'Video translation with lip sync', 'Custom avatar cloning', 'Enterprise-grade features', 'Batch video production'],
    cons: ['Expensive for individuals', 'Avatars can look uncanny', 'Limited creative freedom', 'Not for cinematic content'],
    bestFor: 'AI avatar and business videos',
    simpleDesc: 'Create professional talking-head videos with AI avatars. Translate videos into 40+ languages with lip sync. Popular with businesses for training and marketing.',
    whoFor: 'Businesses, HR teams, marketers, educators',
    url: 'https://heygen.com'
  },

  // === AUDIO & MUSIC ===
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    maker: 'ElevenLabs',
    category: 'audio',
    logo: 'https://cdn.simpleicons.org/elevenlabs/ffffff',
    color: '#f0c27f',
    colorRgb: '240,194,127',
    tagline: 'The voice AI platform',
    model: 'Multilingual v2, Turbo v2.5',
    launched: '2023',
    users: 'a16z All-Star (every list)',
    pricing: { free: '10 min/month free', pro: '$5/mo', top: '$99/mo (Scale)' },
    ratings: { coding: 1.0, writing: 3.0, reasoning: 2.0, speed: 8.5, vision: 1.0, creative: 8.5, value: 8.0 },
    ratingReasons: {
      coding: 'Not a coding tool; focused on voice and audio AI',
      writing: 'Can assist with script formatting but not a writing tool',
      reasoning: 'No analytical reasoning; audio production focused',
      speed: 'Near-instant text-to-speech with real-time voice streaming',
      vision: 'No image capabilities; audio-only tool',
      creative: 'Industry-leading voice cloning and multilingual speech synthesis',
      value: 'Free tier with 10 min/month; Pro from $5/mo is affordable'
    },
    topUseCases: ['Converting text to natural-sounding speech in 29+ languages', 'Cloning voices for personalised audio content', 'Producing audiobook narration and podcast voiceovers'],
    pros: ['Most realistic AI voices', 'Voice cloning in seconds', 'Multi-language support', 'Real-time voice conversion', 'Used for audiobooks & podcasts'],
    cons: ['Minutes-based pricing', 'Deepfake concerns', 'Voice cloning ethical issues', 'Not for text or code'],
    bestFor: 'AI voice generation & cloning',
    simpleDesc: 'Creates the most realistic AI voices available. Clone any voice in seconds. Used for audiobooks, podcasts, and content creation.',
    whoFor: 'Content creators, podcasters, audiobook producers, developers',
    url: 'https://elevenlabs.io'
  },
  {
    id: 'suno',
    name: 'Suno',
    maker: 'Suno',
    category: 'audio',
    logo: 'https://suno.com/favicon.ico',
    color: '#ff4081',
    colorRgb: '255,64,129',
    tagline: 'Make any song you can imagine',
    model: 'Suno v4',
    launched: '2023',
    users: 'a16z Top 50 AI product',
    pricing: { free: '5 songs/day free', pro: '$10/mo (Pro)', top: '$30/mo (Premier)' },
    ratings: { coding: 1.0, writing: 5.0, reasoning: 2.0, speed: 8.0, vision: 1.0, creative: 9.5, value: 8.5 },
    ratingReasons: {
      coding: 'Not a coding tool; AI music generation focused',
      writing: 'Generates song lyrics as part of music creation',
      reasoning: 'No analytical reasoning; music composition focused',
      speed: 'Full songs generated in under a minute',
      vision: 'No image capabilities; audio-only tool',
      creative: 'Best-in-class AI music generation across all genres',
      value: 'Free tier with 5 songs/day; Pro at $10/mo is excellent'
    },
    topUseCases: ['Generating complete songs with lyrics, vocals, and instruments', 'Creating background music and jingles for content', 'Exploring musical creativity across genres without instruments'],
    pros: ['Generate full songs from text', 'Lyrics, vocals, and music', 'Multiple genres & styles', 'Free tier available', 'Surprisingly good quality'],
    cons: ['Copyright concerns with style', 'Not for professional production', 'Songs can sound formulaic', 'Limited control over arrangement'],
    bestFor: 'AI music creation',
    simpleDesc: 'Type a description and get a full song with lyrics, vocals, and instruments. Surprisingly good and very addictive.',
    whoFor: 'Music lovers, content creators, anyone who\'s ever wanted to make a song',
    url: 'https://suno.com'
  },
  {
    id: 'udio',
    name: 'Udio',
    maker: 'Udio',
    category: 'audio',
    logo: 'https://udio.com/favicon.ico',
    color: '#ff3366',
    colorRgb: '255,51,102',
    tagline: 'AI music that sounds real',
    model: 'Udio v1.5',
    launched: '2024',
    users: 'Fast-growing music AI',
    pricing: { free: 'Free tier (limited)', pro: '$10/mo (Standard)', top: '$30/mo (Premium)' },
    ratings: { coding: 1.0, writing: 5.0, reasoning: 2.0, speed: 7.5, vision: 1.0, creative: 9.0, value: 8.0 },
    ratingReasons: {
      coding: 'Not a coding tool; music generation focused',
      writing: 'Generates lyrics as part of song creation with decent quality',
      reasoning: 'No analytical reasoning; music composition focused',
      speed: 'Full tracks generated in under a minute',
      vision: 'No image capabilities; audio-only tool',
      creative: 'Excellent music generation quality rivalling Suno across genres',
      value: 'Free tier available with generous daily generations'
    },
    topUseCases: ['Generating full songs with vocals and instrumentation', 'Creating custom background music for videos and podcasts', 'Exploring music production across genres without instruments'],
    pros: ['Excellent audio fidelity', 'Strong genre versatility', 'Lyrics generation included', 'Free tier available', 'Growing feature set'],
    cons: ['Copyright concerns like Suno', 'Smaller community than Suno', 'Limited arrangement control', 'Still maturing as a platform'],
    bestFor: 'High-fidelity AI music generation',
    simpleDesc: 'Suno\'s main competitor for AI music. Creates full songs with impressive audio fidelity and genre range. Strong free tier.',
    whoFor: 'Musicians, content creators, podcast producers, music enthusiasts',
    url: 'https://udio.com'
  },

  // === RESEARCH & PRODUCTIVITY ===
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    maker: 'Google',
    category: 'research',
    logo: 'https://cdn.simpleicons.org/google/ffffff',
    color: '#34a853',
    colorRgb: '52,168,83',
    tagline: 'Your AI research assistant',
    model: 'Gemini-powered',
    launched: '2024',
    users: '#13 AI web product (a16z)',
    pricing: { free: 'Completely free', pro: 'Plus coming soon', top: 'Enterprise (via Google)' },
    ratings: { coding: 3.0, writing: 8.0, reasoning: 8.5, speed: 8.0, vision: 5.0, creative: 7.5, value: 10.0 },
    ratingReasons: {
      coding: 'Can explain code in documents but not a development tool',
      writing: 'Excellent at summarising and synthesising document content',
      reasoning: 'Strong source-grounded reasoning with zero hallucination design',
      speed: 'Fast document processing and query responses',
      vision: 'Can process images within uploaded documents',
      creative: 'Audio Overview feature creates engaging podcast-style summaries',
      value: 'Completely free — best value proposition in AI research tools'
    },
    topUseCases: ['Turning research papers into easy-to-understand summaries', 'Generating Audio Overviews (AI podcasts) from your documents', 'Querying multiple uploaded sources with grounded answers'],
    pros: ['Completely free', 'Upload docs → AI understands them', 'Audio Overview (AI podcast)', 'Source-grounded answers', 'No hallucinations about your docs'],
    cons: ['Limited to uploaded sources', 'No general web knowledge', 'Google account required', 'Can\'t generate images/code'],
    bestFor: 'Understanding documents & research',
    simpleDesc: 'Upload your documents and NotebookLM becomes an expert on them. Generates summaries, answers questions, and creates AI podcast-style overviews.',
    whoFor: 'Students, researchers, professionals who work with documents',
    url: 'https://notebooklm.google.com'
  },
  {
    id: 'gamma',
    name: 'Gamma',
    maker: 'Gamma',
    category: 'research',
    logo: 'https://gamma.app/favicon.ico',
    color: '#6366f1',
    colorRgb: '99,102,241',
    tagline: 'AI presentations in seconds',
    model: 'Multi-model',
    launched: '2023',
    users: 'a16z All-Star (every list)',
    pricing: { free: 'Free (with Gamma branding)', pro: '$10/mo', top: '$20/mo (Business)' },
    ratings: { coding: 1.0, writing: 7.5, reasoning: 6.0, speed: 9.0, vision: 7.0, creative: 8.0, value: 8.5 },
    ratingReasons: {
      coding: 'Not a coding tool; presentation and document generation focused',
      writing: 'Good at structuring content into clear presentation narratives',
      reasoning: 'Adequate for organising and structuring information logically',
      speed: 'Generates complete presentations in under 30 seconds',
      vision: 'Produces polished visual layouts with embedded media and charts',
      creative: 'Beautiful template-driven designs for professional presentations',
      value: 'Free tier available with branding; Pro at $10/mo removes it'
    },
    topUseCases: ['Creating professional slide decks in seconds from a topic', 'Generating pitch decks and business presentations', 'Building shareable web-based documents with embedded media'],
    pros: ['Full presentations in 30 seconds', 'Beautiful default templates', 'Embeds, charts, and media', 'Share as web page or PDF', 'Way faster than PowerPoint'],
    cons: ['Less customisable than PowerPoint', 'Can feel template-y', 'Not for complex data viz', 'Branding on free tier'],
    bestFor: 'AI-generated presentations',
    simpleDesc: 'Describe your presentation topic and get a polished slide deck in seconds. Faster and prettier than doing it manually.',
    whoFor: 'Anyone who needs to make presentations quickly',
    url: 'https://gamma.app'
  },
  {
    id: 'canva',
    name: 'Canva AI',
    maker: 'Canva',
    category: 'research',
    logo: 'https://cdn.simpleicons.org/canva/ffffff',
    color: '#00c4cc',
    colorRgb: '0,196,204',
    tagline: 'AI design for everyone',
    model: 'Magic Studio (multi-model)',
    launched: '2024',
    users: '190M+ monthly users',
    pricing: { free: 'Free (generous)', pro: '$13/mo (Pro)', top: '$30/mo (Teams)' },
    ratings: { coding: 1.0, writing: 5.0, reasoning: 4.0, speed: 9.0, vision: 8.0, creative: 8.5, value: 8.5 },
    ratingReasons: {
      coding: 'Not a coding tool; design and visual content focused',
      writing: 'Magic Write helps with copy for designs and presentations',
      reasoning: 'Basic content understanding for design suggestions',
      speed: 'Extremely fast AI-powered design generation and editing',
      vision: 'Strong visual output with AI image generation and editing tools',
      creative: 'Excellent for accessible design with AI-powered templates and tools',
      value: 'Free tier is very capable; Pro at $13/mo includes extensive AI features'
    },
    topUseCases: ['Designing social media posts and marketing materials with AI', 'Removing backgrounds and editing photos with Magic Eraser', 'Creating presentations and documents with AI-generated content'],
    pros: ['AI design for non-designers', 'Massive template library', 'Magic Eraser and background removal', 'Brand kit integration', 'Free tier is very capable'],
    cons: ['Not for complex design work', 'Templates can feel generic', 'AI features still maturing', 'Pro required for best AI tools'],
    bestFor: 'Quick AI-powered design for everyone',
    simpleDesc: 'Canva\'s AI-powered Magic Studio makes design accessible to everyone. Create social media posts, presentations, and marketing materials with AI assistance.',
    whoFor: 'Small businesses, social media managers, educators, anyone needing quick designs',
    url: 'https://canva.com'
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    maker: 'Grammarly',
    category: 'research',
    logo: 'https://cdn.simpleicons.org/grammarly/ffffff',
    color: '#15c39a',
    colorRgb: '21,195,154',
    tagline: 'AI writing assistant everywhere',
    model: 'GrammarlyGO (multi-model)',
    launched: '2023',
    users: '30M+ daily users',
    pricing: { free: 'Free (basics)', pro: '$12/mo (Premium)', top: '$15/user/mo (Business)' },
    ratings: { coding: 2.0, writing: 9.0, reasoning: 6.0, speed: 9.5, vision: 1.0, creative: 5.0, value: 7.5 },
    ratingReasons: {
      coding: 'Minimal code support; focused on natural language writing',
      writing: 'Industry-leading grammar, tone, and style correction across all platforms',
      reasoning: 'Understands context for appropriate tone and style suggestions',
      speed: 'Real-time corrections and suggestions as you type anywhere',
      vision: 'No image capabilities; text-only writing assistant',
      creative: 'Helpful for polishing creative work but not for generating it',
      value: 'Free tier covers basics; $12/mo Premium adds tone and clarity features'
    },
    topUseCases: ['Real-time grammar and spelling correction across all apps', 'Adjusting writing tone for professional emails and documents', 'Detecting plagiarism and improving academic writing clarity'],
    pros: ['Works everywhere you type', 'Industry-leading grammar correction', 'Tone and style suggestions', 'GrammarlyGO for AI writing', 'Browser and desktop integration'],
    cons: ['Not a general AI assistant', 'Premium needed for best features', 'Can over-correct style', 'Limited to text correction'],
    bestFor: 'AI-powered writing correction everywhere',
    simpleDesc: 'The world\'s most popular AI writing assistant. Corrects grammar, adjusts tone, and improves clarity everywhere you type — email, docs, social media.',
    whoFor: 'Professionals, students, non-native English writers, anyone who writes',
    url: 'https://grammarly.com'
  },
];

const CATEGORIES = [
  { id: 'coding', name: 'Coding', icon: '💻', desc: 'Writing, debugging & understanding code', simple: 'How good is it at helping you code?' },
  { id: 'writing', name: 'Writing', icon: '✍️', desc: 'Prose, copywriting & content', simple: 'How well does it write?' },
  { id: 'reasoning', name: 'Reasoning', icon: '🧩', desc: 'Logic, analysis & problem solving', simple: 'How smart is it at solving problems?' },
  { id: 'speed', name: 'Speed', icon: '⚡', desc: 'Response time & throughput', simple: 'How fast does it respond?' },
  { id: 'vision', name: 'Vision', icon: '👁️', desc: 'Image understanding & generation', simple: 'Can it see and create images?' },
  { id: 'creative', name: 'Creative', icon: '🎭', desc: 'Imagination & originality', simple: 'How creative and original is it?' },
  { id: 'value', name: 'Value', icon: '💰', desc: 'Features vs price', simple: 'Is it worth the money?' }
];

const USE_CASES = [
  { label: '✍️ Writing', categories: ['assistant'], sortBy: 'writing', desc: 'Find the best AI for writing' },
  { label: '💻 Coding', categories: ['assistant', 'coding'], sortBy: 'coding', desc: 'Find the best AI for code' },
  { label: '🔍 Research', categories: ['assistant', 'research'], sortBy: 'reasoning', desc: 'Find the best AI for research' },
  { label: '🎨 Images', categories: ['image'], sortBy: 'vision', desc: 'Find the best AI for images' },
  { label: '🎬 Video', categories: ['video'], sortBy: 'creative', desc: 'Find the best AI for video' },
  { label: '🎵 Music & Voice', categories: ['audio'], sortBy: 'creative', desc: 'Find the best AI for audio' },
  { label: '🚀 Build an App', categories: ['coding'], sortBy: 'coding', desc: 'Find the best AI to build apps' },
  { label: '💰 Free/Cheap', categories: ['assistant', 'coding', 'research'], sortBy: 'value', desc: 'Best value AI tools' },
];

function getScoreLabel(score) {
  if (score >= 9.0) return 'Elite';
  if (score >= 8.0) return 'Excellent';
  if (score >= 7.0) return 'Strong';
  if (score >= 6.0) return 'Good';
  if (score >= 5.0) return 'Average';
  return 'Limited';
}

function getTierLabel(overall) {
  if (overall >= 9.0) return { tier: 'S', color: '#ffd700' };
  if (overall >= 8.0) return { tier: 'A', color: '#00ff88' };
  if (overall >= 7.0) return { tier: 'B', color: '#00f0ff' };
  if (overall >= 6.0) return { tier: 'C', color: '#ff8800' };
  return { tier: 'N', color: '#ff00aa' };
}
