// AI Arena — Tool Database (Jan 2026, sourced from a16z Top 100 Gen AI + current data)

const TOOL_CATEGORIES = {
  assistant: { name: 'AI Assistants', icon: '💬', desc: 'General-purpose AI chatbots and assistants' },
  coding: { name: 'Coding & App Building', icon: '💻', desc: 'AI tools for writing code and building apps' },
  image: { name: 'Image Generation', icon: '🎨', desc: 'AI tools for creating and editing images' },
  video: { name: 'Video Generation', icon: '🎬', desc: 'AI tools for creating and editing video' },
  audio: { name: 'Audio & Music', icon: '🎵', desc: 'AI tools for voice, music, and audio' },
  research: { name: 'Research & Productivity', icon: '📚', desc: 'AI tools for research, writing, and getting work done' },
};

const TOOLS = [
  // === AI ASSISTANTS ===
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    maker: 'OpenAI',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/openai/ffffff',
    color: '#10a37f',
    colorRgb: '16,163,127',
    tagline: 'The #1 AI assistant in the world',
    model: 'GPT-4o, o3, o1',
    launched: '2022',
    users: '300M+ weekly users',
    pricing: { free: 'Free (GPT-4o mini)', pro: '$20/mo (Plus)', top: '$200/mo (Pro)' },
    ratings: { coding: 8.5, writing: 8.0, reasoning: 9.0, speed: 8.5, vision: 8.5, creative: 8.0, value: 7.0 },
    pros: ['Most popular AI — huge ecosystem', 'GPT Store with custom GPTs', 'Voice & video mode', 'o3 for frontier reasoning', 'Canvas for collaborative editing'],
    cons: ['Pro tier expensive at $200/mo', 'Rate limits frustrate power users', 'Can be verbose and hedgy', 'Plugins ecosystem fragmented'],
    bestFor: 'The default AI for everything',
    simpleDesc: 'The world\'s most popular AI chatbot. Good at almost everything — writing, coding, maths, analysis, images. If you only try one AI tool, this is the one.',
    whoFor: 'Everyone — from students to professionals',
    url: 'https://chat.openai.com'
  },
  {
    id: 'claude',
    name: 'Claude',
    maker: 'Anthropic',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/anthropic/ffffff',
    color: '#d97757',
    colorRgb: '217,119,87',
    tagline: 'The thinking person\'s AI',
    model: 'Opus 4.5, Sonnet 4, Haiku 3.5',
    launched: '2023',
    users: 'Top 5 AI assistant globally',
    pricing: { free: 'Free (Sonnet)', pro: '$20/mo (Pro)', top: '$30/mo (Team)' },
    ratings: { coding: 9.5, writing: 9.5, reasoning: 9.5, speed: 7.5, vision: 8.0, creative: 9.0, value: 8.5 },
    pros: ['Best writing quality of any AI', 'Opus 4.5 — frontier reasoning & code', '200K context window', 'Artifacts — builds apps inline', 'Honest about what it doesn\'t know'],
    cons: ['Smaller ecosystem than ChatGPT', 'Can be cautious on edgy topics', 'Slower on complex tasks', 'No image generation'],
    bestFor: 'Deep thinking, premium writing & code',
    simpleDesc: 'Known for exceptional writing and the deepest thinking. Opus 4.5 is considered one of the best AI models in the world for coding, analysis, and nuanced tasks.',
    whoFor: 'Writers, developers, analysts, and power users who value quality',
    url: 'https://claude.ai'
  },
  {
    id: 'gemini',
    name: 'Gemini',
    maker: 'Google',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/googlegemini/ffffff',
    color: '#4285f4',
    colorRgb: '66,133,244',
    tagline: 'Google\'s AI, everywhere',
    model: 'Gemini 2.0 Flash, 2.0 Pro',
    launched: '2023',
    users: '#2 AI assistant globally',
    pricing: { free: 'Free (very generous)', pro: '$20/mo (Advanced)', top: 'Vertex AI (enterprise)' },
    ratings: { coding: 8.0, writing: 7.5, reasoning: 8.5, speed: 9.0, vision: 9.0, creative: 7.5, value: 9.0 },
    pros: ['Deep Google Workspace integration', '1M+ token context — analyse huge docs', 'Excellent multimodal (images, video, audio)', 'Best free tier of any AI', 'Gemini Live for voice conversations'],
    cons: ['Quality can be inconsistent', 'Creative writing is weaker', 'Sometimes confidently wrong', 'Playing catch-up on coding'],
    bestFor: 'Google users & multimodal tasks',
    simpleDesc: 'Google\'s AI built into Gmail, Docs, Search, and Android. Strongest at understanding images, video, and long documents. Best free tier available.',
    whoFor: 'Google Workspace users, researchers, anyone wanting a capable free AI',
    url: 'https://gemini.google.com'
  },
  {
    id: 'grok',
    name: 'Grok',
    maker: 'xAI',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/x/ffffff',
    color: '#1da1f2',
    colorRgb: '29,161,242',
    tagline: 'The unfiltered one',
    model: 'Grok 4',
    launched: '2023',
    users: '20M+ mobile users',
    pricing: { free: 'Limited via X', pro: '$8/mo (X Premium)', top: '$16/mo (Premium+)' },
    ratings: { coding: 8.0, writing: 7.5, reasoning: 8.5, speed: 8.5, vision: 8.0, creative: 8.5, value: 8.0 },
    pros: ['Grok 4 — strong reasoning & search', 'Real-time X/Twitter data', 'Less filtered than competitors', 'Aurora image generation', 'Cheapest premium AI ($8/mo)'],
    cons: ['Tied to X/Twitter ecosystem', 'Smaller context than Claude/Gemini', 'Less polished interface', 'Limited third-party integrations'],
    bestFor: 'Social media, trending topics & unfiltered AI',
    simpleDesc: 'xAI\'s fast-growing assistant, built into X/Twitter. Less filtered, with real-time access to social data. Grok 4 made it competitive with the best.',
    whoFor: 'X/Twitter users, people who want unfiltered AI, trend watchers',
    url: 'https://grok.x.ai'
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    maker: 'Perplexity AI',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/perplexity/ffffff',
    color: '#20b2aa',
    colorRgb: '32,178,170',
    tagline: 'The answer engine',
    model: 'Sonar, Claude, GPT-4o (multi-model)',
    launched: '2022',
    users: '100M+ monthly users',
    pricing: { free: 'Free (5 Pro/day)', pro: '$20/mo (Pro)', top: '$40/mo (Enterprise)' },
    ratings: { coding: 6.5, writing: 7.5, reasoning: 8.0, speed: 9.0, vision: 6.5, creative: 6.0, value: 9.0 },
    pros: ['Always cites sources — verify anything', 'Real-time web search built in', 'Uses multiple models under the hood', 'Clean, distraction-free UI', 'Excellent for research'],
    cons: ['Weak at creative writing', 'Limited coding help', 'Not great for long conversations', 'Can\'t generate images'],
    bestFor: 'Research & sourced answers',
    simpleDesc: 'A smarter Google. Ask any question, get a clear answer with sources linked. The go-to tool for research and fact-checking.',
    whoFor: 'Researchers, journalists, students, anyone who wants verified answers',
    url: 'https://perplexity.ai'
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    maker: 'DeepSeek AI',
    category: 'assistant',
    logo: 'https://cdn.simpleicons.org/deepseek/ffffff',
    color: '#4d6bfe',
    colorRgb: '77,107,254',
    tagline: 'China\'s open-source challenger',
    model: 'DeepSeek-V3, DeepSeek-R1',
    launched: '2024',
    users: 'Viral growth, top 10 globally',
    pricing: { free: 'Free (web)', pro: 'API: ultra-cheap', top: 'Self-host (open source)' },
    ratings: { coding: 8.5, writing: 7.5, reasoning: 9.0, speed: 8.0, vision: 6.0, creative: 7.0, value: 9.5 },
    pros: ['R1 reasoning rivals o1/o3', 'Extremely cheap API pricing', 'Open source — run it yourself', 'Strong at maths and coding', 'Free web access'],
    cons: ['Chinese company — data concerns', 'English writing weaker than Claude', 'Limited multimodal abilities', 'Web interface basic'],
    bestFor: 'Cheap, powerful reasoning & open-source AI',
    simpleDesc: 'A Chinese AI lab that shocked the industry with models rivalling OpenAI at a fraction of the cost. Free to use and open source.',
    whoFor: 'Budget-conscious users, developers, privacy advocates who self-host',
    url: 'https://chat.deepseek.com'
  },
  {
    id: 'characterai',
    name: 'Character.AI',
    maker: 'Character Technologies',
    category: 'assistant',
    logo: 'https://characterai.io/favicon.ico',
    color: '#8b5cf6',
    colorRgb: '139,92,246',
    tagline: 'Talk to anyone — real or imagined',
    model: 'Custom character models',
    launched: '2022',
    users: '#3 AI on web, 298 sessions/user/month',
    pricing: { free: 'Free (generous)', pro: '$9.99/mo (c.ai+)', top: 'N/A' },
    ratings: { coding: 3.0, writing: 7.0, reasoning: 5.0, speed: 9.0, vision: 3.0, creative: 9.0, value: 9.0 },
    pros: ['Incredibly engaging conversations', 'Millions of characters to talk to', 'Create your own characters', 'Most addictive AI product', 'Great for roleplay & creativity'],
    cons: ['Not for professional work', 'Hallucinations common', 'No web browsing', 'Content filters can be aggressive'],
    bestFor: 'Entertainment, roleplay & AI companionship',
    simpleDesc: 'Chat with AI versions of anyone — fictional characters, celebrities, or custom personalities. The most engaging and addictive AI chat experience.',
    whoFor: 'People wanting entertainment, creative roleplay, or AI companionship',
    url: 'https://character.ai'
  },

  // === CODING & APP BUILDING ===
  {
    id: 'cursor',
    name: 'Cursor',
    maker: 'Cursor Inc',
    category: 'coding',
    logo: 'https://www.cursor.com/favicon.ico',
    color: '#7c3aed',
    colorRgb: '124,58,237',
    tagline: 'The AI code editor',
    model: 'Claude, GPT-4o, custom (multi-model)',
    launched: '2023',
    users: 'Top developer tool',
    pricing: { free: 'Free (limited)', pro: '$20/mo (Pro)', top: '$40/mo (Business)' },
    ratings: { coding: 9.5, writing: 5.0, reasoning: 8.5, speed: 8.5, vision: 6.0, creative: 5.5, value: 8.5 },
    pros: ['Best AI coding experience available', 'Understands your entire codebase', 'Multi-file editing in one go', 'Supports multiple AI models', 'Tab-complete that reads your mind'],
    cons: ['Code-only — not general purpose', 'Can burn through API credits fast', 'Learning curve for full potential', 'VS Code fork — some extensions break'],
    bestFor: 'Professional software development',
    simpleDesc: 'A code editor supercharged with AI. Understands your whole project and writes, edits, and debugs code across files. The tool pro developers love.',
    whoFor: 'Software developers who want to code much faster',
    url: 'https://cursor.com'
  },
  {
    id: 'replit',
    name: 'Replit',
    maker: 'Replit',
    category: 'coding',
    logo: 'https://cdn.simpleicons.org/replit/ffffff',
    color: '#f26522',
    colorRgb: '242,101,34',
    tagline: 'Describe it. Deploy it.',
    model: 'Replit Agent (multi-model)',
    launched: '2024',
    users: 'Top 50 AI web product (a16z)',
    pricing: { free: 'Free (limited)', pro: '$25/mo (Core)', top: '$40/mo (Teams)' },
    ratings: { coding: 8.5, writing: 4.5, reasoning: 7.0, speed: 8.0, vision: 4.0, creative: 5.0, value: 8.0 },
    pros: ['Describe an app → get a working app', 'Instant deployment included', 'Full dev environment in browser', 'Handles backend + frontend + database', 'Great for prototyping fast'],
    cons: ['Less control than local dev', 'Credit system can get expensive', 'Complex apps can be hit-or-miss', 'Limited to web apps'],
    bestFor: 'Building and deploying apps from scratch',
    simpleDesc: 'Tell it what app you want, and it builds the whole thing — frontend, backend, database, and hosting. Ideal for turning ideas into live products.',
    whoFor: 'Entrepreneurs, indie hackers, anyone who wants to ship apps fast',
    url: 'https://replit.com'
  },
  {
    id: 'lovable',
    name: 'Lovable',
    maker: 'Lovable',
    category: 'coding',
    logo: 'https://lovable.dev/favicon.ico',
    color: '#e040fb',
    colorRgb: '224,64,251',
    tagline: 'Vibe code beautiful apps',
    model: 'Claude-powered',
    launched: '2024',
    users: '#22 AI web product (a16z)',
    pricing: { free: 'Free (limited)', pro: '$20/mo (Launch)', top: '$100/mo (Scale)' },
    ratings: { coding: 8.0, writing: 4.0, reasoning: 6.5, speed: 8.5, vision: 7.5, creative: 7.5, value: 7.5 },
    pros: ['Beautiful UI designs by default', 'Supabase backend integration', 'GitHub sync built in', 'Very fast iteration', 'No coding knowledge needed'],
    cons: ['React + Tailwind only', 'Complex logic can struggle', 'Newer platform — still maturing', 'Limited customisation depth'],
    bestFor: 'Beautiful web apps without coding',
    simpleDesc: 'Describe the app you want, get a polished web app with modern design. Syncs with GitHub and integrates databases automatically.',
    whoFor: 'Non-technical creators who want professional-looking apps',
    url: 'https://lovable.dev'
  },
  {
    id: 'bolt',
    name: 'Bolt',
    maker: 'StackBlitz',
    category: 'coding',
    logo: 'https://bolt.new/favicon.ico',
    color: '#ff6b00',
    colorRgb: '255,107,0',
    tagline: 'Prompt. Run. Ship.',
    model: 'Multi-model (Claude, GPT-4o)',
    launched: '2024',
    users: 'a16z Top 100 AI product',
    pricing: { free: 'Free (limited)', pro: '$20/mo', top: '$40/mo (Team)' },
    ratings: { coding: 8.0, writing: 4.0, reasoning: 6.5, speed: 9.0, vision: 5.0, creative: 6.0, value: 8.0 },
    pros: ['Runs code entirely in-browser', 'No setup or deployment needed', 'WebContainer technology = instant', 'Full-stack app generation', 'Multiple model choices'],
    cons: ['Complex apps can be inconsistent', 'Browser-based limitations', 'Newer than Replit/Lovable', 'Less design polish than Lovable'],
    bestFor: 'Instant full-stack prototypes',
    simpleDesc: 'Type a prompt and get a running full-stack app instantly in your browser. No setup, no deployment — it just works.',
    whoFor: 'Developers wanting instant prototypes, vibe coders',
    url: 'https://bolt.new'
  },
  {
    id: 'v0',
    name: 'v0',
    maker: 'Vercel',
    category: 'coding',
    logo: 'https://cdn.simpleicons.org/vercel/ffffff',
    color: '#000000',
    colorRgb: '100,100,100',
    tagline: 'Generate UI with AI',
    model: 'Multi-model',
    launched: '2024',
    users: 'Growing rapidly',
    pricing: { free: 'Free (limited)', pro: '$20/mo (Premium)', top: '$30/mo (Team)' },
    ratings: { coding: 8.0, writing: 3.5, reasoning: 6.0, speed: 8.0, vision: 7.0, creative: 7.5, value: 7.5 },
    pros: ['Beautiful component generation', 'React/Next.js/Tailwind native', 'One-click deploy to Vercel', 'Great shadcn/ui integration', 'Excellent for UI components'],
    cons: ['Frontend-focused only', 'Limited backend generation', 'Vercel ecosystem lock-in', 'Not for full app generation'],
    bestFor: 'Generating UI components and frontends',
    simpleDesc: 'Generate beautiful React UI components from text descriptions. Produces clean, production-ready code using modern frameworks.',
    whoFor: 'Frontend developers, designers who code, React developers',
    url: 'https://v0.dev'
  },
  {
    id: 'devin',
    name: 'Devin',
    maker: 'Cognition',
    category: 'coding',
    logo: 'https://devin.ai/favicon.ico',
    color: '#00d4aa',
    colorRgb: '0,212,170',
    tagline: 'The AI software engineer',
    model: 'Devin (proprietary)',
    launched: '2024',
    users: 'Enterprise early access',
    pricing: { free: 'No', pro: '$500/mo', top: 'Enterprise (custom)' },
    ratings: { coding: 9.0, writing: 4.0, reasoning: 8.5, speed: 5.5, vision: 5.0, creative: 4.5, value: 4.0 },
    pros: ['Truly autonomous — works independently', 'Own browser, terminal & editor', 'Can learn entire codebases', 'Handles multi-step projects', 'Replaces junior dev tasks'],
    cons: ['$500/month — very expensive', 'Slow for simple tasks', 'Quality varies on complex work', 'Overkill for most use cases'],
    bestFor: 'Autonomous development tasks',
    simpleDesc: 'An AI that works like a junior software developer. Give it a task and it plans, codes, tests, and deploys independently over hours.',
    whoFor: 'Engineering teams wanting to automate routine development',
    url: 'https://devin.ai'
  },

  // === IMAGE GENERATION ===
  {
    id: 'midjourney',
    name: 'Midjourney',
    maker: 'Midjourney Inc',
    category: 'image',
    logo: 'https://cdn.simpleicons.org/midjourney/ffffff',
    color: '#ff6b35',
    colorRgb: '255,107,53',
    tagline: 'The AI artist',
    model: 'Midjourney v6.1',
    launched: '2022',
    users: 'a16z All-Star (every list)',
    pricing: { free: 'No free tier', pro: '$10/mo (Basic)', top: '$60/mo (Mega)' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 7.5, vision: 9.5, creative: 9.5, value: 8.0 },
    pros: ['Stunning artistic image quality', 'Consistent style and aesthetics', 'Great for branding & marketing', 'Active creative community', 'Photorealistic capability'],
    cons: ['No free tier', 'Mostly Discord-based', 'Cannot do text or code', 'Prompt crafting learning curve'],
    bestFor: 'Beautiful AI-generated images',
    simpleDesc: 'Creates stunning AI images from text descriptions. The gold standard for artistic, marketing, and design visuals.',
    whoFor: 'Designers, marketers, content creators, artists',
    url: 'https://midjourney.com'
  },
  {
    id: 'leonardo',
    name: 'Leonardo.AI',
    maker: 'Leonardo AI',
    category: 'image',
    logo: 'https://leonardo.ai/favicon.ico',
    color: '#9333ea',
    colorRgb: '147,51,234',
    tagline: 'Creative AI for everyone',
    model: 'Phoenix, Flux, SDXL',
    launched: '2023',
    users: 'a16z All-Star (every list)',
    pricing: { free: '150 tokens/day free', pro: '$10/mo', top: '$48/mo' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 8.0, vision: 9.0, creative: 9.0, value: 8.5 },
    pros: ['Generous free tier', 'Multiple model choices', 'Real-time canvas editing', 'Great for game & concept art', 'Web-based (no Discord needed)'],
    cons: ['Less consistent than Midjourney', 'Token system can be confusing', 'Learning curve for best results', 'Photorealism slightly behind'],
    bestFor: 'Accessible AI image creation',
    simpleDesc: 'A web-based AI art studio with multiple models, a free tier, and real-time editing. More accessible than Midjourney with similar quality.',
    whoFor: 'Digital artists, game developers, anyone wanting free AI images',
    url: 'https://leonardo.ai'
  },

  // === VIDEO ===
  {
    id: 'runway',
    name: 'Runway',
    maker: 'Runway',
    category: 'video',
    logo: 'https://runwayml.com/favicon.ico',
    color: '#00c2ff',
    colorRgb: '0,194,255',
    tagline: 'The AI video studio',
    model: 'Gen-3 Alpha Turbo',
    launched: '2023',
    users: 'Leading AI video tool',
    pricing: { free: '125 credits free', pro: '$12/mo', top: '$76/mo (Unlimited)' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 7.0, vision: 9.0, creative: 9.0, value: 7.0 },
    pros: ['Best-in-class AI video generation', 'Text-to-video and image-to-video', 'Professional editing tools', 'Motion brush control', 'Used by Hollywood studios'],
    cons: ['Credits used up quickly', 'Short clips (5-10 seconds)', 'Expensive for heavy use', 'Faces can be uncanny'],
    bestFor: 'AI video generation and editing',
    simpleDesc: 'Create short AI videos from text or images. Used by filmmakers and marketers. The most established AI video tool.',
    whoFor: 'Video creators, filmmakers, marketers, social media managers',
    url: 'https://runwayml.com'
  },
  {
    id: 'sora',
    name: 'Sora',
    maker: 'OpenAI',
    category: 'video',
    logo: 'https://cdn.simpleicons.org/openai/ffffff',
    color: '#10a37f',
    colorRgb: '16,163,127',
    tagline: 'OpenAI\'s video model',
    model: 'Sora',
    launched: '2024',
    users: 'Available via ChatGPT Pro',
    pricing: { free: 'No (ChatGPT Plus needed)', pro: '$20/mo (via Plus)', top: '$200/mo (via Pro)' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 2.0, speed: 6.0, vision: 9.5, creative: 9.0, value: 6.0 },
    pros: ['Incredible visual quality', 'Longer clips than competitors', 'Physics understanding', 'Text-to-video & image-to-video', 'Storyboard mode'],
    cons: ['Only via ChatGPT subscription', 'Slow generation times', 'Very limited monthly generations', 'Content policy restrictions'],
    bestFor: 'Highest quality AI video',
    simpleDesc: 'OpenAI\'s video generator creates stunningly realistic short videos. Limited access but the highest quality AI video available.',
    whoFor: 'Filmmakers, marketers wanting premium AI video',
    url: 'https://sora.com'
  },

  // === AUDIO & MUSIC ===
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    maker: 'ElevenLabs',
    category: 'audio',
    logo: 'https://cdn.simpleicons.org/elevenlabs/ffffff',
    color: '#f0c27f',
    colorRgb: '240,194,127',
    tagline: 'The voice AI platform',
    model: 'Multilingual v2, Turbo v2.5',
    launched: '2023',
    users: 'a16z All-Star (every list)',
    pricing: { free: '10 min/month free', pro: '$5/mo', top: '$99/mo (Scale)' },
    ratings: { coding: 1.0, writing: 3.0, reasoning: 2.0, speed: 8.5, vision: 1.0, creative: 8.5, value: 8.0 },
    pros: ['Most realistic AI voices', 'Voice cloning in seconds', 'Multi-language support', 'Real-time voice conversion', 'Used for audiobooks & podcasts'],
    cons: ['Minutes-based pricing', 'Deepfake concerns', 'Voice cloning ethical issues', 'Not for text or code'],
    bestFor: 'AI voice generation & cloning',
    simpleDesc: 'Creates the most realistic AI voices available. Clone any voice in seconds. Used for audiobooks, podcasts, and content creation.',
    whoFor: 'Content creators, podcasters, audiobook producers, developers',
    url: 'https://elevenlabs.io'
  },
  {
    id: 'suno',
    name: 'Suno',
    maker: 'Suno',
    category: 'audio',
    logo: 'https://suno.com/favicon.ico',
    color: '#ff4081',
    colorRgb: '255,64,129',
    tagline: 'Make any song you can imagine',
    model: 'Suno v4',
    launched: '2023',
    users: 'a16z Top 50 AI product',
    pricing: { free: '5 songs/day free', pro: '$10/mo (Pro)', top: '$30/mo (Premier)' },
    ratings: { coding: 1.0, writing: 5.0, reasoning: 2.0, speed: 8.0, vision: 1.0, creative: 9.5, value: 8.5 },
    pros: ['Generate full songs from text', 'Lyrics, vocals, and music', 'Multiple genres & styles', 'Free tier available', 'Surprisingly good quality'],
    cons: ['Copyright concerns with style', 'Not for professional production', 'Songs can sound formulaic', 'Limited control over arrangement'],
    bestFor: 'AI music creation',
    simpleDesc: 'Type a description and get a full song with lyrics, vocals, and instruments. Surprisingly good and very addictive.',
    whoFor: 'Music lovers, content creators, anyone who\'s ever wanted to make a song',
    url: 'https://suno.com'
  },

  // === RESEARCH & PRODUCTIVITY ===
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    maker: 'Google',
    category: 'research',
    logo: 'https://cdn.simpleicons.org/google/ffffff',
    color: '#34a853',
    colorRgb: '52,168,83',
    tagline: 'Your AI research assistant',
    model: 'Gemini-powered',
    launched: '2024',
    users: '#13 AI web product (a16z)',
    pricing: { free: 'Completely free', pro: 'Plus coming soon', top: 'Enterprise (via Google)' },
    ratings: { coding: 3.0, writing: 8.0, reasoning: 8.5, speed: 8.0, vision: 5.0, creative: 7.5, value: 10.0 },
    pros: ['Completely free', 'Upload docs → AI understands them', 'Audio Overview (AI podcast)', 'Source-grounded answers', 'No hallucinations about your docs'],
    cons: ['Limited to uploaded sources', 'No general web knowledge', 'Google account required', 'Can\'t generate images/code'],
    bestFor: 'Understanding documents & research',
    simpleDesc: 'Upload your documents and NotebookLM becomes an expert on them. Generates summaries, answers questions, and creates AI podcast-style overviews.',
    whoFor: 'Students, researchers, professionals who work with documents',
    url: 'https://notebooklm.google.com'
  },
  {
    id: 'gamma',
    name: 'Gamma',
    maker: 'Gamma',
    category: 'research',
    logo: 'https://gamma.app/favicon.ico',
    color: '#6366f1',
    colorRgb: '99,102,241',
    tagline: 'AI presentations in seconds',
    model: 'Multi-model',
    launched: '2023',
    users: 'a16z All-Star (every list)',
    pricing: { free: 'Free (with Gamma branding)', pro: '$10/mo', top: '$20/mo (Business)' },
    ratings: { coding: 1.0, writing: 7.5, reasoning: 6.0, speed: 9.0, vision: 7.0, creative: 8.0, value: 8.5 },
    pros: ['Full presentations in 30 seconds', 'Beautiful default templates', 'Embeds, charts, and media', 'Share as web page or PDF', 'Way faster than PowerPoint'],
    cons: ['Less customisable than PowerPoint', 'Can feel template-y', 'Not for complex data viz', 'Branding on free tier'],
    bestFor: 'AI-generated presentations',
    simpleDesc: 'Describe your presentation topic and get a polished slide deck in seconds. Faster and prettier than doing it manually.',
    whoFor: 'Anyone who needs to make presentations quickly',
    url: 'https://gamma.app'
  },
];

const CATEGORIES = [
  { id: 'coding', name: 'Coding', icon: '💻', desc: 'Writing, debugging & understanding code', simple: 'How good is it at helping you code?' },
  { id: 'writing', name: 'Writing', icon: '✍️', desc: 'Prose, copywriting & content', simple: 'How well does it write?' },
  { id: 'reasoning', name: 'Reasoning', icon: '🧩', desc: 'Logic, analysis & problem solving', simple: 'How smart is it at solving problems?' },
  { id: 'speed', name: 'Speed', icon: '⚡', desc: 'Response time & throughput', simple: 'How fast does it respond?' },
  { id: 'vision', name: 'Vision', icon: '👁️', desc: 'Image understanding & generation', simple: 'Can it see and create images?' },
  { id: 'creative', name: 'Creative', icon: '🎭', desc: 'Imagination & originality', simple: 'How creative and original is it?' },
  { id: 'value', name: 'Value', icon: '💰', desc: 'Features vs price', simple: 'Is it worth the money?' }
];

const USE_CASES = [
  { label: '✍️ Writing', categories: ['assistant'], sortBy: 'writing', desc: 'Find the best AI for writing' },
  { label: '💻 Coding', categories: ['assistant', 'coding'], sortBy: 'coding', desc: 'Find the best AI for code' },
  { label: '🔍 Research', categories: ['assistant', 'research'], sortBy: 'reasoning', desc: 'Find the best AI for research' },
  { label: '🎨 Images', categories: ['image'], sortBy: 'vision', desc: 'Find the best AI for images' },
  { label: '🎬 Video', categories: ['video'], sortBy: 'creative', desc: 'Find the best AI for video' },
  { label: '🎵 Music & Voice', categories: ['audio'], sortBy: 'creative', desc: 'Find the best AI for audio' },
  { label: '🚀 Build an App', categories: ['coding'], sortBy: 'coding', desc: 'Find the best AI to build apps' },
  { label: '💰 Free/Cheap', categories: ['assistant', 'coding', 'research'], sortBy: 'value', desc: 'Best value AI tools' },
];

function getScoreLabel(score) {
  if (score >= 9.0) return 'Elite';
  if (score >= 8.0) return 'Excellent';
  if (score >= 7.0) return 'Strong';
  if (score >= 6.0) return 'Good';
  if (score >= 5.0) return 'Average';
  return 'Limited';
}

function getTierLabel(overall) {
  if (overall >= 9.0) return { tier: 'S', color: '#ffd700' };
  if (overall >= 8.0) return { tier: 'A', color: '#00ff88' };
  if (overall >= 7.0) return { tier: 'B', color: '#00f0ff' };
  if (overall >= 6.0) return { tier: 'C', color: '#ff8800' };
  return { tier: 'N', color: '#ff00aa' };
}
