const TOOLS = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    maker: 'OpenAI',
    icon: '⚡',
    color: '#10a37f',
    tagline: 'The OG that started it all',
    pricing: { free: 'Yes', pro: '$20/mo', enterprise: '$60/mo' },
    ratings: { coding: 8.5, writing: 8.0, reasoning: 8.5, speed: 8.0, vision: 8.5, creative: 8.0, value: 7.5 },
    pros: ['Massive plugin ecosystem', 'GPT Store & custom GPTs', 'Great all-rounder', 'Voice & video mode'],
    cons: ['Can be verbose', 'Rate limits on free tier', 'Expensive at scale'],
    bestFor: 'All-purpose AI companion',
    url: 'https://chat.openai.com'
  },
  {
    id: 'claude',
    name: 'Claude',
    maker: 'Anthropic',
    icon: '🧠',
    color: '#d97757',
    tagline: 'The thoughtful heavyweight',
    pricing: { free: 'Yes', pro: '$20/mo', enterprise: 'Custom' },
    ratings: { coding: 9.0, writing: 9.5, reasoning: 9.5, speed: 7.5, vision: 8.0, creative: 9.0, value: 8.5 },
    pros: ['Best writing quality', '200K context window', 'Artifacts & Canvas', 'Honest & nuanced'],
    cons: ['Smaller ecosystem', 'Can be cautious', 'No plugin store'],
    bestFor: 'Deep thinking, writing & code',
    url: 'https://claude.ai'
  },
  {
    id: 'gemini',
    name: 'Gemini',
    maker: 'Google',
    icon: '💎',
    color: '#4285f4',
    tagline: 'Google\'s multimodal beast',
    pricing: { free: 'Yes', pro: '$20/mo', enterprise: 'Via Vertex' },
    ratings: { coding: 8.0, writing: 7.5, reasoning: 8.5, speed: 8.5, vision: 9.0, creative: 7.5, value: 8.0 },
    pros: ['Deep Google integration', '1M+ token context', 'Strong multimodal', 'Free tier generous'],
    cons: ['Inconsistent quality', 'Privacy concerns', 'Sometimes hallucinate'],
    bestFor: 'Google ecosystem & multimodal tasks',
    url: 'https://gemini.google.com'
  },
  {
    id: 'copilot',
    name: 'Copilot',
    maker: 'Microsoft',
    icon: '🤖',
    color: '#0078d4',
    tagline: 'AI meets Office suite',
    pricing: { free: 'Yes', pro: '$30/mo', enterprise: '$30/user/mo' },
    ratings: { coding: 8.5, writing: 7.5, reasoning: 7.5, speed: 8.0, vision: 7.5, creative: 7.0, value: 7.0 },
    pros: ['Office 365 integration', 'GitHub Copilot for code', 'Enterprise ready', 'Bing search built-in'],
    cons: ['Expensive for full suite', 'Jack of all trades', 'UI can be clunky'],
    bestFor: 'Enterprise & Microsoft power users',
    url: 'https://copilot.microsoft.com'
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    maker: 'Perplexity AI',
    icon: '🔍',
    color: '#20b2aa',
    tagline: 'The answer engine',
    pricing: { free: 'Yes', pro: '$20/mo', enterprise: 'Custom' },
    ratings: { coding: 6.5, writing: 7.5, reasoning: 8.0, speed: 9.0, vision: 6.5, creative: 6.5, value: 8.5 },
    pros: ['Real-time web search', 'Source citations', 'Clean UI', 'Fast answers'],
    cons: ['Weaker at creative tasks', 'Limited coding help', 'Less conversational'],
    bestFor: 'Research & fact-checking',
    url: 'https://perplexity.ai'
  },
  {
    id: 'grok',
    name: 'Grok',
    maker: 'xAI',
    icon: '🚀',
    color: '#1da1f2',
    tagline: 'The unfiltered rebel',
    pricing: { free: 'Via X', pro: '$8/mo (X Premium)', enterprise: 'N/A' },
    ratings: { coding: 7.5, writing: 7.5, reasoning: 8.0, speed: 8.5, vision: 7.5, creative: 8.0, value: 7.5 },
    pros: ['Real-time X/Twitter data', 'Unfiltered responses', 'Image generation', 'Humor mode'],
    cons: ['X ecosystem lock-in', 'Less polished', 'Smaller context'],
    bestFor: 'Social media & trending topics',
    url: 'https://grok.x.ai'
  },
  {
    id: 'cursor',
    name: 'Cursor',
    maker: 'Cursor Inc',
    icon: '📝',
    color: '#7c3aed',
    tagline: 'The AI code editor',
    pricing: { free: 'Limited', pro: '$20/mo', enterprise: '$40/mo' },
    ratings: { coding: 9.5, writing: 5.0, reasoning: 8.0, speed: 8.5, vision: 6.0, creative: 5.5, value: 8.5 },
    pros: ['Best coding experience', 'Multi-file editing', 'Codebase-aware', 'Multiple model support'],
    cons: ['Code-only focus', 'Learning curve', 'Can burn through API credits'],
    bestFor: 'Professional software development',
    url: 'https://cursor.sh'
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    maker: 'Midjourney Inc',
    icon: '🎨',
    color: '#ff6b35',
    tagline: 'The visual artist',
    pricing: { free: 'No', pro: '$10-60/mo', enterprise: 'Custom' },
    ratings: { coding: 1.0, writing: 2.0, reasoning: 3.0, speed: 7.5, vision: 9.5, creative: 9.5, value: 8.0 },
    pros: ['Stunning image quality', 'Consistent style', 'Great for branding', 'Active community'],
    cons: ['No free tier', 'Discord-only (web in beta)', 'No text/code ability'],
    bestFor: 'Visual content & design',
    url: 'https://midjourney.com'
  },
  {
    id: 'replit',
    name: 'Replit AI',
    maker: 'Replit',
    icon: '🔧',
    color: '#f26522',
    tagline: 'Code, deploy, ship',
    pricing: { free: 'Yes', pro: '$25/mo', enterprise: 'Custom' },
    ratings: { coding: 8.5, writing: 4.5, reasoning: 7.0, speed: 8.0, vision: 4.0, creative: 5.0, value: 8.0 },
    pros: ['Instant deployment', 'Full dev environment', 'AI builds full apps', 'Great for prototypes'],
    cons: ['Less control than local', 'Can get expensive', 'Quality varies'],
    bestFor: 'Rapid prototyping & deployment',
    url: 'https://replit.com'
  },
  {
    id: 'lovable',
    name: 'Lovable',
    maker: 'Lovable',
    icon: '💜',
    color: '#e040fb',
    tagline: 'Vibe code your dream app',
    pricing: { free: 'Limited', pro: '$20/mo', enterprise: 'Custom' },
    ratings: { coding: 8.0, writing: 4.0, reasoning: 6.5, speed: 8.5, vision: 7.0, creative: 7.0, value: 7.5 },
    pros: ['Beautiful UI by default', 'Supabase integration', 'Fast iteration', 'No-code friendly'],
    cons: ['Limited customisation', 'React/Tailwind only', 'Newer platform'],
    bestFor: 'Beautiful web apps fast',
    url: 'https://lovable.dev'
  },
  {
    id: 'llama',
    name: 'Llama',
    maker: 'Meta',
    icon: '🦙',
    color: '#1877f2',
    tagline: 'Open-source powerhouse',
    pricing: { free: 'Yes (open source)', pro: 'Self-hosted costs', enterprise: 'Via cloud providers' },
    ratings: { coding: 7.5, writing: 7.0, reasoning: 7.5, speed: 9.0, vision: 6.5, creative: 7.0, value: 9.5 },
    pros: ['Free & open source', 'Run locally', 'Full data control', 'Great community'],
    cons: ['Requires technical setup', 'Needs good hardware', 'Behind frontier models'],
    bestFor: 'Privacy-first & self-hosted AI',
    url: 'https://llama.meta.com'
  },
  {
    id: 'devin',
    name: 'Devin',
    maker: 'Cognition',
    icon: '👨‍💻',
    color: '#00d4aa',
    tagline: 'The AI software engineer',
    pricing: { free: 'No', pro: '$500/mo', enterprise: 'Custom' },
    ratings: { coding: 9.0, writing: 4.0, reasoning: 8.5, speed: 6.0, vision: 5.0, creative: 4.5, value: 5.0 },
    pros: ['Autonomous coding agent', 'Full dev environment', 'Can learn codebases', 'Handles complex tasks'],
    cons: ['Very expensive', 'Slow for simple tasks', 'Still early stage', 'Overkill for most'],
    bestFor: 'Complex autonomous development',
    url: 'https://devin.ai'
  }
];

const CATEGORIES = [
  { id: 'coding', name: 'Coding', icon: '💻', desc: 'Writing, debugging & understanding code' },
  { id: 'writing', name: 'Writing', icon: '✍️', desc: 'Prose, copywriting & content creation' },
  { id: 'reasoning', name: 'Reasoning', icon: '🧩', desc: 'Logic, analysis & problem solving' },
  { id: 'speed', name: 'Speed', icon: '⚡', desc: 'Response time & throughput' },
  { id: 'vision', name: 'Vision', icon: '👁️', desc: 'Image understanding & generation' },
  { id: 'creative', name: 'Creative', icon: '🎭', desc: 'Imagination, humor & originality' },
  { id: 'value', name: 'Value', icon: '💰', desc: 'Bang for your buck' }
];
